### ISSUE TITLE
installing process?

### ISSUE THREAD

**Issue by ChobbarSaab** [shubhambalyan/income-tax-returns-processing-made-easy#1]
sir how to run this project?

**Comment by shubhambalyan** [comment]
First, you will have to download the XAMPP server and run the "Apache" and "SQL" servers. Put the code files in the "htdocs" sub-directory inside the "XAMPP" directory. Create the database schema shown in the project description in "phpmyadmin", and then open the "index.html" page on any browser. This is a very general way of running any web-based application on the xampp server.
